services:

  frontend:
    build: ./frontend
    container_name: acortador-frontend
    ports:
      - "80:80"
    depends_on:
      - api
  api:
    build: ./backend
    container_name: acortador-api
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://db:6379
    depends_on:
      - db
  db:
    image: redis:alpine
    container_name: acortador-redis
    volumes:
      - redis_data:/data
volumes:
  redis_data: